# Generated by Django 3.2.13 on 2022-07-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0014_rename_expenditure_expenditure_exp'),
        ('works', '0003_alter_workexpenditure_projectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=124)),
                ('complainttext', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('complaintdate', models.DateField(auto_now=True)),
                ('upload', models.FileField(upload_to='uploads')),
                ('projectname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.newworks')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ureg')),
            ],
        ),
    ]
