# Generated by Django 3.2.13 on 2022-09-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0016_expenditure_status'),
        ('works', '0003_alter_workexpenditure_projectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=124)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('depositdate', models.DateField(auto_now=True)),
                ('projectname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.newworks')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ureg')),
            ],
        ),
    ]
