# Generated by Django 3.2.13 on 2022-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='hash',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='prevhash',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
    ]
