# Generated by Django 3.2.13 on 2022-11-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_expenditure_status'),
        ('works', '0007_alter_purchaseinterest_status'),
        ('donate', '0002_auto_20220927_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('depositdate', models.DateField(auto_now=True)),
                ('prevhash', models.CharField(blank=True, max_length=224, null=True)),
                ('hash', models.CharField(blank=True, max_length=224, null=True)),
                ('projectname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.property')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ureg')),
            ],
        ),
    ]
