# Generated by Django 3.2.13 on 2022-07-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0003_alter_workexpenditure_projectname'),
        ('app', '0014_rename_expenditure_expenditure_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttext', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('commentdate', models.DateField(auto_now=True)),
                ('projectname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.newworks')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ureg')),
            ],
        ),
    ]
