# Generated by Django 3.2.13 on 2022-07-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectDetails', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('FundDetails', models.CharField(max_length=200)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.district')),
            ],
        ),
    ]
