# Generated by Django 3.2.13 on 2022-07-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('exp', models.IntegerField()),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.district')),
            ],
        ),
    ]
