# Generated by Django 3.2.13 on 2022-07-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_workexpenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexpenditure',
            name='ProjectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.newworks'),
        ),
    ]
