# Generated by Django 3.2.13 on 2022-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_workexpenditure_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexpenditure',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
