# Generated by Django 3.2.13 on 2022-11-24 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_expenditure_status'),
        ('works', '0004_workexpenditure_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationDetails', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Surveyno', models.IntegerField()),
                ('PriceValue', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('Tosell', models.BooleanField(default=False)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.district')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ureg')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentdate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ureg')),
                ('PropertyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.property')),
            ],
        ),
    ]
