# Generated by Django 3.2.13 on 2022-11-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_expenditure_status'),
        ('works', '0005_ownership_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priceoffered', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('Interestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ureg')),
                ('PropertyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.property')),
            ],
        ),
    ]
