# Generated by Django 3.2.13 on 2022-11-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_purchaseinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinterest',
            name='status',
            field=models.CharField(default='Waiting', max_length=20),
        ),
    ]
